carga_horaria/urls.py
from . import views

app_name = 'carga-horaria'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^assign/$', views.assign, name='assign'),
    url(r'^switch/$', views.switch, name='switch'),
    url(r'^switch/(?P<pk>\d+)/$', views.switch, name='switch'),
    url(r'^switch-periodo/(?P<year>\d+)/$', views.switch_periodo, name='switch-periodo'),
    url(r'^clear/$', views.clear, name='clear'),
    url(
        r'^profesores/$',
        views.ProfesorListView.as_view(),
        name='profesores'
    ),
    url(
        r'^profesores/pdf/$',
        views.profesores_pdf,
        name='profesores-pdf'
    ),
    url(
        r'^profesores/excel/$',
        views.profesores_info,
        name='profesores-info'
    ),
    url(
        r'^profesores/excel-auto/$',
        views.profesores_auto,
        name='profesores-auto'
    ),
    url(
        r'^profesores/uploadFile/$',
        views.uploadFile,
        name='uploadFile'
    ),
    url(
        r'^profesores/excel-directivos/$',
        views.profesores_directivos,
        name='profesores-directivos'
    ),
    url(
        r'^asistentes/excel/$',
        views.asistentes_info,
        name='asistentes-info'
    ),
    url(
        r'^profesores/(?P<pk>\d+)/$',
        views.ProfesorDetailView.as_view(),
        name='profesor'
    ),
    url(
        r'^profesores/(?P<pk>\d+)/anexo/$',
        views.anexo,
        name='profesor__anexo'
    ),
    url(
        r'^profesores/anexos/$',
        views.anexos,
        name='profesor__anexos'
    ),
    url(
        r'^profesores/nuevo/$',
        views.ProfesorCreateView.as_view(),
        name='profesor__nuevo'
    ),
    url(
        r'^profesores/(?P<pk>\d+)/editar/$',
        views.ProfesorUpdateView.as_view(),
        name='profesor__editar'
    ),
    url(
        r'^profesores/(?P<pk>\d+)/eliminar/$',
        views.ProfesorDeleteView.as_view(),
        name='profesor__eliminar'
    ),
    # url(
    #     r'^cursos/$',
    #     views.CursoListView.as_view(),
    #     name='cursos'
    # ),
    # url(
    #     r'^cursos/(?P<pk>\d+)/$',
    #     views.CursoDetailView.as_view(),
    #     name='curso'
    # ),
    # url(
    #     r'^cursos/nuevo/$',
    #     views.CursoCreateView.as_view(),
    #     name='curso__nuevo'
    # ),
    # url(
    #     r'^cursos/(?P<pk>\d+)/editar/$',
    #     views.CursoUpdateView.as_view(),
    #     name='curso__editar'
    # ),
    # url(
    #     r'^cursos/(?P<pk>\d+)/eliminar/$',
    #     views.CursoDeleteView.as_view(),
    #     name='curso__eliminar'
    # ),
    url(
        r'^asistentes/$',
        views.AsistenteListView.as_view(),
        name='asistentes'
    ),
    url(
        r'^asistentes/pdf/$',
        views.asistentes_pdf,
        name='asistentes-pdf'
    ),
    url(
        r'^asistentes/(?P<pk>\d+)/$',
        views.AsistenteDetailView.as_view(),
        name='asistente'
    ),
    url(
        r'^asistentes/nuevo/$',
        views.AsistenteCreateView.as_view(),
        name='asistente__nuevo'
    ),
    url(
        r'^asistentes/(?P<pk>\d+)/editar/$',
        views.AsistenteUpdateView.as_view(),
        name='asistente__editar'
    ),
    url(
        r'^asistentes/(?P<pk>\d+)/eliminar/$',
        views.AsistenteDeleteView.as_view(),
        name='asistente__eliminar'
    ),
    url(
        r'^asistentes/(?P<pk>\d+)/anexo/$',
        views.anexo_asistente,
        name='asistente__anexo'
    ),
    url(
        r'^asistentes/anexos/$',
        views.anexos_asistentes,
        name='asistente__anexos'
    ),
    url(
        r'^asignaturasbase/$',
        views.AsignaturaBaseListView.as_view(),
        name='asignaturasbase'
    ),
    url(
        r'^asignaturasbase/(?P<pk>\d+)/$',
        views.AsignaturaBaseDetailView.as_view(),
        name='asignaturabase'
    ),
    url(
        r'^asignaturasbase/nuevo/$',
        views.AsignaturaBaseCreateView.as_view(),
        name='asignaturabase__nuevo'
    ),
    url(
        r'^asignaturasbase/(?P<pk>\d+)/editar/$',
        views.AsignaturaBaseUpdateView.as_view(),
        name='asignaturabase__editar'
    ),
    url(
        r'^asignaturasbase/(?P<pk>\d+)/eliminar/$',
        views.AsignaturaBaseDeleteView.as_view(),
        name='asignaturabase__eliminar'
    ),
    # url(
    #     r'^asignaturas/$',
    #     views.AsignaturaListView.as_view(),
    #     name='asignaturas'
    # ),
    url(
        r'^asignaturas/(?P<pk>\d+)/(?P<periodo_pk>\d+)/$',
        views.AsignaturaDetailView.as_view(),
        name='asignatura'
    ),
    url(
        r'^asignaturas/(?P<pk>\d+)/limpiar/(?P<periodo_pk>\d+)/$',
        views.asignatura_limpiar,
        name='asignatura__limpiar'
    ),
    url(
        r'^periodos/(?P<pk>\d+)/nueva-asignatura/$',
        views.AsignaturaCreateView.as_view(),
        name='asignatura__nuevo'
    ),
    url(
        r'^periodos/(?P<pk>\d+)/nueva-asignatura-dif/$',
        views.asignatura_dif,
        name='asignatura_dif__nuevo'
    ),
    url(
        r'^periodos/(?P<pk>\d+)/nueva-asignatura-maybe/$',
        views.asignatura_maybe,
        name='asignatura_maybe'
    ),
    url(
        r'^periodos/(?P<pk>\d+)/nueva-asignatura-merge/(?P<asignatura_pk>\d+)/$',
        views.asignatura_merge,
        name='asignatura_merge'
    ),
    url(
        r'^asignaturas/(?P<pk>\d+)/editar/(?P<periodo_pk>\d+)/$',
        views.AsignaturaUpdateView.as_view(),
        name='asignatura__editar'
    ),
    url(
        r'^asignaturas/(?P<pk>\d+)/eliminar/(?P<periodo_pk>\d+)/$',
        views.AsignaturaDeleteView.as_view(),
        name='asignatura__eliminar'
    ),

    url(
        r'^periodos/$',
        views.PeriodoListView.as_view(),
        name='periodos'
    ),
    url(
        r'^periodos/(?P<pk>\d+)/$',
        views.PeriodoDetailView.as_view(),
        name='periodo'
    ),
    url(
        r'^periodos/(?P<pk>\d+)/pdf/$',
        views.periodo_pdf,
        name='periodo-pdf'
    ),
    url(
        r'^periodos/nuevo/$',
        views.PeriodoCreateView.as_view(),
        name='periodo__nuevo'
    ),
    url(
        r'^periodos/(?P<pk>\d+)/editar/$',
        views.PeriodoUpdateView.as_view(),
        name='periodo__editar'
    ),
    url(
        r'^periodos/(?P<pk>\d+)/eliminar/$',
        views.PeriodoDeleteView.as_view(),
        name='periodo__eliminar'
    ),

    url(
        r'^colegios/$',
        views.ColegioListView.as_view(),
        name='colegios'
    ),
    url(
        r'^colegios/(?P<pk>\d+)/$',
        views.ColegioDetailView.as_view(),
        name='colegio'
    ),
    url(
        r'^colegios/nuevo/$',
        views.ColegioCreateView.as_view(),
        name='colegio__nuevo'
    ),
    url(
        r'^colegios/(?P<pk>\d+)/editar/$',
        views.ColegioUpdateView.as_view(),
        name='colegio__editar'
    ),
    url(
        r'^colegios/(?P<pk>\d+)/eliminar/$',
        views.ColegioDeleteView.as_view(),
        name='colegio__eliminar'
    ),
    url(
        r'^planes/$',
        views.PlanListView.as_view(),
        name='planes'
    ),
    url(
        r'^planes/(?P<pk>\d+)/$',
        views.PlanDetailView.as_view(),
        name='plan'
    ),
    url(
        r'^planes/nuevo/$',
        views.PlanCreateView.as_view(),
        name='plan__nuevo'
    ),
    url(
        r'^planes/(?P<pk>\d+)/editar/$',
        views.PlanUpdateView.as_view(),
        name='plan__editar'
    ),
    url(
        r'^planes/(?P<pk>\d+)/actualizar/$',
        views.plan_refresh,
        name='plan__actualizar'
    ),
    url(
        r'^planes/(?P<pk>\d+)/eliminar/$',
        views.PlanDeleteView.as_view(),
        name='plan__eliminar'
    ),
    url(
        r'^asignaturas/(?P<pk>\d+)/asignar/(?P<periodo_pk>\d+)/$',
        views.asignar,
        name='asignar'
    ),
    url(
        r'^profesores/(?P<pk>\d+)/fua/(?P<tipo>\d+)/$',
        views.asignar_fua,
        name='asignar-fua'
    ),
    url(
        r'^profesores/(?P<pk>\d+)/no-aula-fua/(?P<tipo>\d+)/$',
        views.asignar_no_aula_fua,
        name='asignar-no-aula-fua'
    ),
    url(
        r'^asignaciones/(?P<pk>\d+)/editar/$',
        views.AsignacionUpdateView.as_view(),
        name='asignacion__editar'
    ),
    url(
        r'^asignaciones/(?P<pk>\d+)/eliminar/(?P<profesor_pk>\d+)/$',
        views.AsignacionDeleteView.as_view(),
        name='asignacion__eliminar'
    ),
    url(
        r'^profesores/(?P<pk>\d+)/asignar-extra/$',
        views.asignar_extra,
        name='asignar-extra'
    ),
    url(
        r'^profesores/(?P<profesor_pk>\d+)/asignaciones-extra/(?P<pk>\d+)/editar/$',
        views.AsignacionExtraUpdateView.as_view(),
        name='asignacion-extra__editar'
    ),
    url(
        r'^asignaciones-extra/(?P<pk>\d+)/eliminar/$',
        views.AsignacionExtraDeleteView.as_view(),
        name='asignacion-extra__eliminar'
    ),
    url(
        r'^profesores/(?P<pk>\d+)/asignar-no-aula/$',
        views.asignar_no_aula,
        name='asignar-no-aula'
    ),
    url(
        r'^profesores/(?P<profesor_pk>\d+)/asignaciones-no-aula/(?P<pk>\d+)/editar/$',
        views.AsignacionNoAulaUpdateView.as_view(),
        name='asignacion-no-aula__editar'
    ),
    url(
        r'^asignaciones-no-aula/(?P<pk>\d+)/eliminar/$',
        views.AsignacionNoAulaDeleteView.as_view(),
        name='asignacion-no-aula__eliminar'
    ),
    #################
    url(
        r'^asistentes/(?P<pk>\d+)/asignar/(?P<tipo>\d+)$',
        views.asignar_asistente,
        name='asignar-asistente'
    ),
    # url(
    #     r'^asistentes/(?P<profesor_pk>\d+)/asignaciones/(?P<pk>\d+)/editar/$',
    #     views.AsignacionExtraUpdateView.as_view(),
    #     name='asignacion-extra__editar'
    # ),
    url(
        r'^asignaciones-asistente/(?P<pk>\d+)/eliminar/$',
        views.AsignacionAsistenteDeleteView.as_view(),
        name='asignacion-asistente__eliminar'
    ),
    ####################
    url(
        r'^planes/plantila/$',
        views.crear_desde_plantilla,

rrhh/urls.py
from django.conf import settings
from django.conf.urls import url
from rrhh import views

app_name = 'rrhh'

urlpatterns = [
    url(r'^$', views.home, name='home_rrhh'),
    url(r'^hyper_index/$', views.hyper_index, name='hyper_index'),
    url(
        r'^personas/$',
        views.PersonaListView.as_view(),
        name='personas'
    ),
    url(
        r'^personas/nuevo/$',
        views.PersonaCreateView.as_view(),
        name='persona__nuevo'
    ),
    url(
        r'^personas/(?P<pk_persona>\d+)/$',
        views.persona_detail,
        name='persona'
    ),
    url(
        r'^personas/(?P<pk>\d+)/editar/$',
        views.PersonaUpdateView.as_view(),
        name='persona__editar'
    ),
    url(
        r'^personas/(?P<pk>\d+)/eliminar/$',
        views.PersonaDeleteView.as_view(),
        name='persona__eliminar'
    ),
    # url(
    #     r'^funcionarios/$',
    #     views.FuncionarioListView.as_view(),
    #     name='funcionarios'
    # ),
    url(
        r'^funcionarios/(?P<id_persona>\d+)/nuevo/$',
        views.crear_funcionario,
        name='funcionario__nuevo'
    ),
    # url(
    #     r'^funcionarios/(?P<pk>\d+)/$',
    #     views.FuncionarioDetailView.as_view(),
    #     name='funcionario'
    # ),
    url(
        r'^funcionarios/(?P<pk>\d+)/editar/$',
        views.FuncionarioUpdateView.as_view(),
        name='funcionario__editar'
    ),
    # url(
    #     r'^funcionarios/(?P<pk>\d+)/eliminar/$',
    #     views.FuncionarioDeleteView.as_view(),
    #     name='funcionario__eliminar'
    # ),
    url(
        r'^postulantes/$',
        views.postulantes,
        name='postulantes'
    ),
    url(
        r'^entrevistas/$',
        views.EntrevistaListView.as_view(),
        name='entrevistas'
    ),
    url(
        r'^entrevistas/nuevo/$',
        views.EntrevistaCreateView.as_view(),
        name='entrevista__nuevo'
    ),
    url(
        r'^entrevistas/(?P<pk>\d+)/$',
        views.EntrevistaDetailView.as_view(),
        name='entrevista'
    ),
    url(
        r'^entrevistas/nuevo/$',
        views.EntrevistaCreateView.as_view(),
        name='entrevista__nuevo'
    ),
    url(
        r'^entrevistas/(?P<pk>\d+)/editar/$',
        views.EntrevistaUpdateView.as_view(),
        name='entrevista__editar'
    ),
    url(
        r'^entrevistas/(?P<pk>\d+)/eliminar/$',
        views.EntrevistaDeleteView.as_view(),
        name='entrevista__eliminar'
    ),
    url(
        r'^documentos/$',
        views.DocumentoListView.as_view(),
        name='documentos'
    ),
    url(
        r'^documentos/nuevo/$',
        views.DocumentoCreateView.as_view(),
        name='documento__nuevo'
    ),
    url(
        r'^documentos/(?P<pk>\d+)/$',
        views.DocumentoDetailView.as_view(),
        name='documento'
    ),
    url(
        r'^documentos/nuevo/$',
        views.DocumentoCreateView.as_view(),
        name='documento__nuevo'
    ),
    url(
        r'^documentos/(?P<pk>\d+)/editar/$',
        views.DocumentoUpdateView.as_view(),
        name='documento__editar'
    ),
    url(
        r'^documentos/(?P<pk>\d+)/eliminar/$',
        views.DocumentoDeleteView.as_view(),
        name='documento__eliminar'
    ),
    url(
        r'^vacaciones/$',
        views.VacacionListView.as_view(),
        name='vacaciones'
    ),
    url(
        r'^vacaciones/nuevo/$',
        views.VacacionCreateView.as_view(),
        name='vacacion__nuevo'
    ),
    url(
        r'^vacaciones/(?P<pk>\d+)/$',
        views.VacacionDetailView.as_view(),
        name='vacacion'
    ),
    url(
        r'^vacaciones/(?P<pk>\d+)/editar/$',
        views.VacacionUpdateView.as_view(),
        name='vacacion__editar'
    ),
    url(
        r'^vacaciones/(?P<pk>\d+)/eliminar/$',
        views.VacacionDeleteView.as_view(),
        name='vacacion__eliminar'
    ),
    url(
        r'^licencias/$',
        views.LicenciaListView.as_view(),
        name='licencias'
    ),
    url(
        r'^licencias/nuevo/$',
        views.LicenciaCreateView.as_view(),
        name='licencia__nuevo'
    ),
    url(
        r'^licencias/(?P<pk>\d+)/$',
        views.LicenciaDetailView.as_view(),
        name='licencia'
    ),
    url(
        r'^licencias/(?P<pk>\d+)/editar/$',
        views.LicenciaUpdateView.as_view(),
        name='licencia__editar'
    ),
    url(
        r'^licencias/(?P<pk>\d+)/eliminar/$',
        views.LicenciaDeleteView.as_view(),
        name='licencia__eliminar'
    ),
    url(
        r'^licencias_funcionario/nuevo/$',
        views.nuevo_licencia_tipo_funcionario,
        name='licencia_funcionario__nuevo'
    ),
    url(
        r'^permisos/$',
        views.PermisoListView.as_view(),
        name='permisos'
    ),
    url(
        r'^permisos/nuevo/$',
        views.PermisoCreateView.as_view(),
        name='permiso__nuevo'
    ),
    url(
        r'^permisos/(?P<pk>\d+)/$',
        views.PermisoDetailView.as_view(),
        name='permiso'
    ),
    url(
        r'^permisos/(?P<pk>\d+)/editar/$',
        views.PermisoUpdateView.as_view(),
        name='permiso__editar'
    ),
    url(
        r'^permisos/(?P<pk>\d+)/eliminar/$',
        views.PermisoDeleteView.as_view(),
        name='permiso__eliminar'
    ),
    url(
        r'^permisos_funcionario/nuevo/$',
        views.nuevo_permiso_tipo_funcionario,
        name='permiso_funcionario__nuevo'
    ),
    url(
        r'^vacaciones_funcionario/nuevo/$',
        views.nuevo_vacacion_funcionario,
        name='vacacion_funcionario__nuevo'
    ),
    url(
        r'^contratos/nuevo/(?P<id_funcionario>\d+)/(?P<id_solicitud>\d+)/',
        views.crear_contrato,
        name='contrato__crear'
    ),
    url(
        r'^contratos/$',
        views.ContratoListView.as_view(),
        name='contratos'
    ),
    url(
        r'^contratos/nuevo/$',
        views.ContratoCreateView.as_view(),
        name='contrato__nuevo'
    ),
    url(
        r'^contratos/(?P<pk>\d+)/$',
        views.ContratoDetailView.as_view(),
        name='contrato'
    ),
    url(
        r'^contratos/(?P<pk>\d+)/editar/$',
        views.ContratoUpdateView.as_view(),
        name='contrato__editar'
    ),
    url(
        r'^contratos/(?P<pk>\d+)/eliminar/$',
        views.ContratoDeleteView.as_view(),
        name='contrato__eliminar'
    ),
    url(
        r'^contratos/(?P<pk>\d+)/contrato/$',
        views.detalle_contrato_pdf,
        name='detalle-contrato-pdf'
    ),
    url(
        r'^contratos/(?P<pk>\d+)/reglamento/$',
        views.Toma_conocimiento_reglamento_interno_pdf,
        name='toma-conocimiento-reglamento-interno-pdf'
    ),
    url(
        r'^contratos/(?P<pk>\d+)/diezmo/$',
        views.detalle_trabajador_diezmo_pdf,
        name='detalle-trabajador-diezmo-pdf'
    ),
    url(
        r'^contratos/(?P<pk>\d+)/image/$',
        views.autorizacion_imagen_pdf,
        name='autorizacion-imagen-pdf'
    ),
    url(
        r'^estado-contratacion/cambiar/$',
        views.cambiar_estado_contratacion,
        name='estado_contratacion__cambiar'
    ),
    url(
        r'^finiquito/(?P<id_contrato>\d+)/$',
        views.nuevo_finiquito,
        name='finiquito__nuevo'
    ),
    url(
        r'^finiquitos/(?P<pk>\d+)/eliminar/$',
        views.FiniquitoDeleteView.as_view(),
        name='finiquito__eliminar'
    ),
    url(
        r'^solicitudes/$',
        views.SolicitudListView.as_view(),
        name='solicitudes'
    ),
    url(
        r'^solicitudes/nuevo/$',
        views.SolicitudCreateView.as_view(),
        name='solicitud__nuevo'
    ),
    url(
        r'^solicitudes/(?P<pk>\d+)/$',
        views.SolicitudDetailView.as_view(),
        name='solicitud'
    ),
    url(
        r'^solicitudes/(?P<pk>\d+)/editar/$',
        views.SolicitudUpdateView.as_view(),
        name='solicitud__editar'
    ),
    url(
        r'^solicitudes/(?P<pk>\d+)/eliminar/$',
        views.SolicitudDeleteView.as_view(),
        name='solicitud__eliminar'
    ),
    url(
        r'^estado-solicitud/cambiar/$',
        views.cambiar_estado_solicitud,
        name='estado_solicitud__cambiar'
    ),
    url(
        r'^solicitudes/(?P<id_solicitud>\d+)/seleccionar_cadidatos/$',
        views.seleccionar_candidatos,
        name='candidatos__seleccionar'
    ),
    url(
        r'^solicitudes/guardar_candidato/$',
        views.guardar_candidato,
        name='candidatos__guardar'
    ),
    url(
        r'^contratos/(?P<id_contrato>\d+)/renovar/$',
        views.renovar_contrato,
        name='contrato__renovar'
    ),
    url(
        r'^funcionario/(?P<id_contrato>\d+)/trasladar/$',
        views.trasladar_funcionario,
        name='funcionario__trasladar'
    ),
    url(
        r'^funcionario/cargar_documento/$',
        views.cargar_documento_personal,
        name='personal__cargar_documento'
    ),
    url(
        r'^documento_funcionario/nuevo/$',
        views.cargar_documento_personal,
        name='documento_funcionario__nuevo'
    ),
]

# add static
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carga_horaria/templates/carga_horaria/plan/eliminar_planes.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="card-body card-padding">
        <form action="." method="post">
            {% csrf_token %}
            <div class="alert alert-danger" role="alert">
                <h4 class="alert-heading"><i class="uil-exclamation-triangle"></i> Alerta - Eliminar Plan</h4>
                <hr>
                <p>Estás seguro que deseas eliminar el registro de plan <strong> "{{ object.nombre }}" </strong>?</p>
                <br>
                <p><strong>Recuerda que todos los registros asociados a este Plan, serán eliminados. </strong></p>           
            </div>
            <button href="{% url 'carga-horaria:plan' object.pk %}" class="btn btn-outline-dark">
                <i class="uil-arrow-left"></i>
                Cancelar
            </button>
            <button type="submit" class="btn btn-outline-danger">
                <i class="uil-trash"></i>
                   Eliminar
            </button>
        </form>
    </div>

{% endblock content %}

carga_horaria/templates/carga_horaria/plan/listado_planes.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% load bootstrap_pagination %}

{% block title_page %}
    Planes
{% endblock %}

{% block title %}
    Planes
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Suite AAGE</a></li>
    <li class="breadcrumb-item"><a href="{% url 'carga-horaria:home' %}">Carga Horaria</a></li>
    <li class="breadcrumb-item active">Planes</li>
{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header">
        <h4 class="card-title">Listado de Planes
            <div class="btn-group float-right" role="group">
                <a class="btn btn-outline-primary" href="{% url 'carga-horaria:plan__nuevo'%}" role="button">Crear nuevo plan
                    <i class="uil-plus"></i>
                </a>
            </div>
            <div class="btn-group float-right" role="group">
	            <a class="btn btn-outline-success" href="{% url 'carga-horaria:plan__plantilla'%}" role="button">Crear desde plantilla
                    <i class="uil-plus"></i>
                </a>
            </div>
        </h4>
        <h6 class="card-subtitle mb-2 text-muted">Tabla para configuración de Planes</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th><i class="uil-book-open"></i> Plan </th>
                <th style="text-align: center;"><i class="uil-cog"></i> Acciones </th>
            </tr>
            </thead>
            <tbody>
            {% for p in object_list %}
                <tr>
                    <td><a href="{% url 'carga-horaria:plan' p.pk %}">{{ p }}</a></td>
                    <td style="text-align: center;">
                      <a class="btn btn-outline-success" href="{% url 'carga-horaria:plan__actualizar' p.pk %}" data-toggle="tooltip" data-placement="top" title="Actualizar"><i class="uil-refresh"></i></a>
                      <a class="btn btn-outline-primary" href="{% url 'carga-horaria:plan__editar' p.pk %}" data-toggle="tooltip" data-placement="top" title="Editar"><i class="uil-edit"></i></a>
                      <a class="btn btn-outline-danger" href="#" data-toggle="modal" data-target="#eliminar_plan_{{p.pk}}"><i class="uil-trash"></i></a>
                    </td>
                </tr>
                <div class="modal" tabindex="-1" role="dialog" id="eliminar_plan_{{p.pk}}">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title"><strong style="color:red;">¡Alerta!</strong> Está a punto de eliminar un Plan</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <p>Está seguro que desea eliminar el Plan "{{p.nombre}}"?.</p>
                                <p class="text-muted">Recuerde que eliminará todos los registros asociados a este Plan.</p>
                            </div>
                            <div class="modal-footer">
                                <a role="button" class="btn btn-outline-danger" href="{% url 'carga-horaria:plan__eliminar' p.pk %}">Eliminar</a>
                                <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cerrar</button>
                            </div>
                        </div>
                    </div>    
                </div>
            {% endfor %}
            </tbody>
        </table>
    </div>

    </div>

                    <div class="card-footer">
                    <div align="center">
                        {% bootstrap_paginate page_obj range=5 %}
                    </div>
                </div>


</div>

{% endblock content  %}

carga_horaria/templates/carga_horaria/plan/nuevo_plan.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title_page %}
    Crear Plan
{% endblock %}

{% block title %}
    Crear Plan
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Suite AAGE</a></li>
    <li class="breadcrumb-item"><a href="{% url 'carga-horaria:home' %}">Carga Horaria</a></li>
    <li class="breadcrumb-item"><a href="{% url 'carga-horaria:planes' %}">Planes</a></li>
    <li class="breadcrumb-item active">Crear Plan</li>
{% endblock %}


{% block content %}
<div class="card">
    <div class="card-header">
        <h4 class="card-title">Crear Plan
        </h4>
        <h6 class="card-subtitle mb-2 text-muted">Tabla para configuración de un nuevo plan</h6>
    </div>
    <div class="card-body">
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% crispy form %}
            <div class="form-group">
                <div class="col-sm-10 col-sm-offset-2">
                    <button type="submit" class="btn btn-outline-success">Guardar</button>
                    <a {% if object %}
                        href="{% url 'carga-horaria:plan' object.pk %}"
                    {% else %}
                        href="{% url 'carga-horaria:planes' %}"
                    {% endif %}
                    role="button" class="btn btn-outline-dark">
                        Volver
                    </a>
                </div>
            </div>
        </form>
    </div>

    </div>
</div>


{% endblock %}