rrhh/urls.py
from django.conf import settings
from django.conf.urls import url
from rrhh import views

app_name = 'rrhh'

urlpatterns = [
    url(r'^$', views.home, name='home_rrhh'),
    url(r'^hyper_index/$', views.hyper_index, name='hyper_index'),
    url(
        r'^personas/$',
        views.PersonaListView.as_view(),
        name='personas'
    ),
    url(
        r'^personas/nuevo/$',
        views.PersonaCreateView.as_view(),
        name='persona__nuevo'
    ),
    url(
        r'^personas/(?P<pk_persona>\d+)/$',
        views.persona_detail,
        name='persona'
    ),
    url(
        r'^personas/(?P<pk>\d+)/editar/$',
        views.PersonaUpdateView.as_view(),
        name='persona__editar'
    ),
    url(
        r'^personas/(?P<pk>\d+)/eliminar/$',
        views.PersonaDeleteView.as_view(),
        name='persona__eliminar'
    ),
    # url(
    #     r'^funcionarios/$',
    #     views.FuncionarioListView.as_view(),
    #     name='funcionarios'
    # ),
    url(
        r'^funcionarios/(?P<id_persona>\d+)/nuevo/$',
        views.crear_funcionario,
        name='funcionario__nuevo'
    ),
    # url(
    #     r'^funcionarios/(?P<pk>\d+)/$',
    #     views.FuncionarioDetailView.as_view(),
    #     name='funcionario'
    # ),
    url(
        r'^funcionarios/(?P<pk>\d+)/editar/$',
        views.FuncionarioUpdateView.as_view(),
        name='funcionario__editar'
    ),
    # url(
    #     r'^funcionarios/(?P<pk>\d+)/eliminar/$',
    #     views.FuncionarioDeleteView.as_view(),
    #     name='funcionario__eliminar'
    # ),
    url(
        r'^postulantes/$',
        views.postulantes,
        name='postulantes'
    ),
    url(
        r'^entrevistas/$',
        views.EntrevistaListView.as_view(),
        name='entrevistas'
    ),
    url(
        r'^entrevistas/nuevo/$',
        views.EntrevistaCreateView.as_view(),
        name='entrevista__nuevo'
    ),
    url(
        r'^entrevistas/(?P<pk>\d+)/$',
        views.EntrevistaDetailView.as_view(),
        name='entrevista'
    ),
    url(
        r'^entrevistas/nuevo/$',
        views.EntrevistaCreateView.as_view(),
        name='entrevista__nuevo'
    ),
    url(
        r'^entrevistas/(?P<pk>\d+)/editar/$',
        views.EntrevistaUpdateView.as_view(),
        name='entrevista__editar'
    ),
    url(
        r'^entrevistas/(?P<pk>\d+)/eliminar/$',
        views.EntrevistaDeleteView.as_view(),
        name='entrevista__eliminar'
    ),
    url(
        r'^documentos/$',
        views.DocumentoListView.as_view(),
        name='documentos'
    ),
    url(
        r'^documentos/nuevo/$',
        views.DocumentoCreateView.as_view(),
        name='documento__nuevo'
    ),
    url(
        r'^documentos/(?P<pk>\d+)/$',
        views.DocumentoDetailView.as_view(),
        name='documento'
    ),
    url(
        r'^documentos/nuevo/$',
        views.DocumentoCreateView.as_view(),
        name='documento__nuevo'
    ),
    url(
        r'^documentos/(?P<pk>\d+)/editar/$',
        views.DocumentoUpdateView.as_view(),
        name='documento__editar'
    ),
    url(
        r'^documentos/(?P<pk>\d+)/eliminar/$',
        views.DocumentoDeleteView.as_view(),
        name='documento__eliminar'
    ),
    url(
        r'^vacaciones/$',
        views.VacacionListView.as_view(),
        name='vacaciones'
    ),
    url(
        r'^vacaciones/nuevo/$',
        views.VacacionCreateView.as_view(),
        name='vacacion__nuevo'
    ),
    url(
        r'^vacaciones/(?P<pk>\d+)/$',
        views.VacacionDetailView.as_view(),
        name='vacacion'
    ),
    url(
        r'^vacaciones/(?P<pk>\d+)/editar/$',
        views.VacacionUpdateView.as_view(),
        name='vacacion__editar'
    ),
    url(
        r'^vacaciones/(?P<pk>\d+)/eliminar/$',
        views.VacacionDeleteView.as_view(),
        name='vacacion__eliminar'
    ),
    url(
        r'^licencias/$',
        views.LicenciaListView.as_view(),
        name='licencias'
    ),
    url(
        r'^licencias/nuevo/$',
        views.LicenciaCreateView.as_view(),
        name='licencia__nuevo'
    ),
    url(
        r'^licencias/(?P<pk>\d+)/$',
        views.LicenciaDetailView.as_view(),
        name='licencia'
    ),
    url(
        r'^licencias/(?P<pk>\d+)/editar/$',
        views.LicenciaUpdateView.as_view(),
        name='licencia__editar'
    ),
    url(
        r'^licencias/(?P<pk>\d+)/eliminar/$',
        views.LicenciaDeleteView.as_view(),
        name='licencia__eliminar'
    ),
    url(
        r'^licencias_funcionario/nuevo/$',
        views.nuevo_licencia_tipo_funcionario,
        name='licencia_funcionario__nuevo'
    ),
    url(
        r'^permisos/$',
        views.PermisoListView.as_view(),
        name='permisos'
    ),
    url(
        r'^permisos/nuevo/$',
        views.PermisoCreateView.as_view(),
        name='permiso__nuevo'
    ),
    url(
        r'^permisos/(?P<pk>\d+)/$',
        views.PermisoDetailView.as_view(),
        name='permiso'
    ),
    url(
        r'^permisos/(?P<pk>\d+)/editar/$',
        views.PermisoUpdateView.as_view(),
        name='permiso__editar'
    ),
    url(
        r'^permisos/(?P<pk>\d+)/eliminar/$',
        views.PermisoDeleteView.as_view(),
        name='permiso__eliminar'
    ),
    url(
        r'^permisos_funcionario/nuevo/$',
        views.nuevo_permiso_tipo_funcionario,
        name='permiso_funcionario__nuevo'
    ),
    url(
        r'^vacaciones_funcionario/nuevo/$',
        views.nuevo_vacacion_funcionario,
        name='vacacion_funcionario__nuevo'
    ),
    url(
        r'^contratos/nuevo/(?P<id_funcionario>\d+)/(?P<id_solicitud>\d+)/',
        views.crear_contrato,
        name='contrato__crear'
    ),
    url(
        r'^contratos/$',
        views.ContratoListView.as_view(),
        name='contratos'
    ),
    url(
        r'^contratos/nuevo/$',
        views.ContratoCreateView.as_view(),
        name='contrato__nuevo'
    ),
    url(
        r'^contratos/(?P<pk>\d+)/$',
        views.ContratoDetailView.as_view(),
        name='contrato'
    ),
    url(
        r'^contratos/(?P<pk>\d+)/editar/$',
        views.ContratoUpdateView.as_view(),
        name='contrato__editar'
    ),
    url(
        r'^contratos/(?P<pk>\d+)/eliminar/$',
        views.ContratoDeleteView.as_view(),
        name='contrato__eliminar'
    ),
    url(
        r'^contratos/(?P<pk>\d+)/contrato/$',
        views.detalle_contrato_pdf,
        name='detalle-contrato-pdf'
    ),
    url(
        r'^contratos/(?P<pk>\d+)/reglamento/$',
        views.Toma_conocimiento_reglamento_interno_pdf,
        name='toma-conocimiento-reglamento-interno-pdf'
    ),
    url(
        r'^contratos/(?P<pk>\d+)/diezmo/$',
        views.detalle_trabajador_diezmo_pdf,
        name='detalle-trabajador-diezmo-pdf'
    ),
    url(
        r'^contratos/(?P<pk>\d+)/image/$',
        views.autorizacion_imagen_pdf,
        name='autorizacion-imagen-pdf'
    ),
    url(
        r'^estado-contratacion/cambiar/$',
        views.cambiar_estado_contratacion,
        name='estado_contratacion__cambiar'
    ),
    url(
        r'^finiquito/(?P<id_contrato>\d+)/$',
        views.nuevo_finiquito,
        name='finiquito__nuevo'
    ),
    url(
        r'^finiquitos/(?P<pk>\d+)/eliminar/$',
        views.FiniquitoDeleteView.as_view(),
        name='finiquito__eliminar'
    ),
    url(
        r'^solicitudes/$',
        views.SolicitudListView.as_view(),
        name='solicitudes'
    ),
    url(
        r'^solicitudes/nuevo/$',
        views.SolicitudCreateView.as_view(),
        name='solicitud__nuevo'
    ),
    url(
        r'^solicitudes/(?P<pk>\d+)/$',
        views.SolicitudDetailView.as_view(),
        name='solicitud'
    ),
    url(
        r'^solicitudes/(?P<pk>\d+)/editar/$',
        views.SolicitudUpdateView.as_view(),
        name='solicitud__editar'
    ),
    url(
        r'^solicitudes/(?P<pk>\d+)/eliminar/$',
        views.SolicitudDeleteView.as_view(),
        name='solicitud__eliminar'
    ),
    url(
        r'^estado-solicitud/cambiar/$',
        views.cambiar_estado_solicitud,
        name='estado_solicitud__cambiar'
    ),
    url(
        r'^solicitudes/(?P<id_solicitud>\d+)/seleccionar_cadidatos/$',
        views.seleccionar_candidatos,
        name='candidatos__seleccionar'
    ),
    url(
        r'^solicitudes/guardar_candidato/$',
        views.guardar_candidato,
        name='candidatos__guardar'
    ),
    url(
        r'^contratos/(?P<id_contrato>\d+)/renovar/$',
        views.renovar_contrato,
        name='contrato__renovar'
    ),
    url(
        r'^funcionario/(?P<id_contrato>\d+)/trasladar/$',
        views.trasladar_funcionario,
        name='funcionario__trasladar'
    ),
    url(
        r'^funcionario/cargar_documento/$',
        views.cargar_documento_personal,
        name='personal__cargar_documento'
    ),
    url(
        r'^documento_funcionario/nuevo/$',
        views.cargar_documento_personal,
        name='documento_funcionario__nuevo'
    ),
]

# add static
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rrhh/models/persona.py
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from rrhh.models.base import *
from rrhh.models.entidad import Entidad, Contrato

NIVEL_ACCESO = (
    (1, 'Invitado'),
    (2, 'Docente'),
    (3, 'Docente administrativo'),
    (4, 'Director'),
    (5, 'Departamental'),
    (6, 'Asesor'),
    (7, 'Administrador'),
)


class PerfilUsuario(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    perfil = models.ForeignKey("Perfil", on_delete=models.CASCADE)
    nivel_acceso = models.PositiveSmallIntegerField(default=1, choices=NIVEL_ACCESO, verbose_name='Nivel de acceso')

    @property
    def es_admin(self):
        return True if self.usuario.is_staff or self.nivel_acceso == 7 else False

    @property
    def es_asesor(self):
        return True if self.nivel_acceso >= 6 else False

    @property
    def es_departamental(self):
        return True if self.nivel_acceso >= 5 else False

    @property
    def es_director(self):
        return True if self.nivel_acceso >= 4 else False

    @property
    def es_admin_ue(self):
        return True if self.nivel_acceso >= 3 else False

    @property
    def es_docente(self):
        return True if self.nivel_acceso >= 2 else False

    def __str__(self):
        return '{}, {} ({})'.format(
            self.usuario,
            self.perfil,
            self.nivel_acceso
        )

    class Meta:
        verbose_name = u'Perfil de usuario'
        verbose_name_plural = u'Perfiles de usuarios'


class Persona(models.Model):
    GENERO = (
        ('femenino', 'Femenino'),
        ('masculino', 'Masculino')
    )
    NACIONALIDAD = (
        ('chilena', 'Chilena'),
        ('extranjera', 'Extranjera')
    )
    ESTADO_CIVIL = (
        ('soltero', 'Soltero'),
        ('casado', 'Casado'),
        ('divorsiado', 'Divorsiado'),
        ('viudo', 'Viudo')
    )

    rut = models.CharField(max_length=16, unique=True)
    nombres = models.CharField(max_length=255)
    apellido_paterno = models.CharField(max_length=255)
    apellido_materno = models.CharField(max_length=255)
    genero = models.CharField(max_length=100, default='masculino', choices=GENERO, null=True, blank=True, verbose_name='Género')
    fecha_nacimiento = models.DateField(null=True, blank=True, verbose_name='Fecha de nacimiento')
    nacionalidad = models.CharField(max_length=100, default='chilena', choices=NACIONALIDAD)
    estado_civil = models.CharField(max_length=100, default='soltero', choices=ESTADO_CIVIL)
    religion = models.BooleanField(default=True, verbose_name='Adventista del Séptimo día')
    direccion = models.CharField(max_length=255, null=True, blank=True, verbose_name='Dirección')
    ciudad = models.ForeignKey('Ciudad', on_delete=models.SET_NULL, null=True, blank=True)
    telefono = models.PositiveIntegerField(null=True, blank=True, verbose_name='Teléfono', help_text='Número de 9 dígitos')
    email = models.EmailField(null=True, blank=True)
    titulado = models.BooleanField(default=False)
    profesion = models.CharField(max_length=255, null=True, blank=True, verbose_name='Título profesional', default='')
    usuario = models.OneToOneField(User, null=True, blank=True, on_delete=models.SET_NULL)
    foto = models.FileField(null=True, blank=True, upload_to="rrhh/fotos", verbose_name='Foto de perfil')
    curriculum = models.FileField(null=True, blank=True, upload_to="rrhh/curriculums")

    @property
    def get_name(self):
        return '{} {} {}'.format(
            self.nombres.split(' ')[0],
            self.apellido_paterno,
            self.apellido_materno
        )

    @property
    def get_short_name(self):
        return '{} {}'.format(
            self.nombres.split(' ')[0],
            self.apellido_paterno
        )

    @property
    def get_full_name(self):
        return '{} {} {}'.format(
            self.nombres,
            self.apellido_paterno,
            self.apellido_materno
        )

    @property
    def apellidos(self):
        return '{} {}'.format(
            self.apellido_paterno,
            self.apellido_materno
        )

    @property
    def clasificacion(self):
        clasificacion = 'Postulante'
        try:
            if self.funcionario.contrato_set.all():
                clasificacion = 'Postulante SEA'
            if self.funcionario.contrato_set.filter(vigente=True):
                clasificacion = 'Funcionario'
        except:
            pass
        return clasificacion

    @property
    def historial(self):
        return {
            'contratos': self.funcionario.contrato_set.all(),
        }

    def save(self, *args, **kwargs):
        self.nombres = self.nombres.title()
        self.apellido_paterno = self.apellido_paterno.title()
        self.apellido_materno = self.apellido_materno.title()
        self.direccion = self.direccion.title() if self.direccion else None
        self.profesion = self.profesion.title() if self.profesion else None
        self.email = self.email.lower() if self.email else None
        return super(Persona, self).save(*args, **kwargs)

    def __str__(self):
        return '{} {} {} ({})'.format(
            self.nombres,
            self.apellido_paterno,
            self.apellido_materno,
            self.rut
        )

    class Meta:
        verbose_name = u'Persona'
        verbose_name_plural = u'Personas'


class Perfeccionamiento(models.Model):
    persona = models.ForeignKey('Persona', on_delete=models.CASCADE)
    titulo = models.CharField(max_length=255, verbose_name='Nombre del título')
    es_educacion = models.BooleanField(default=True, verbose_name="Títulado en educación")
    area_titulo = models.ForeignKey(
        "AreaTitulo",
        on_delete=models.CASCADE,
        null=True, blank=True,
        verbose_name="Área del título"
    )
    especialidad = models.ForeignKey("Especialidad", on_delete=models.CASCADE, null=True, blank=True)
    mencion = models.ForeignKey("Mencion", on_delete=models.CASCADE, null=True, blank=True, verbose_name="Mención")
    grado_academico = models.CharField(max_length=255, verbose_name='Grado académico')
    fecha_titulacion = models.DateField(verbose_name="Fecha de titulación")
    casa_formadora = models.CharField(max_length=255)

    def __str__(self):
        return '{}, {}'.format(
            self.persona.get_full_name,
            self.titulo
        )

    class Meta:
        verbose_name = u'Perfeccionamiento de persona'
        verbose_name_plural = u'Perfeccionamientos de personas'


class Funcionario(models.Model):
    persona = models.OneToOneField('Persona', on_delete=models.CASCADE)
    salud = models.PositiveSmallIntegerField(default=1, choices=PREVISION_SALUD, verbose_name='Sistema de salud')
    isapre = models.ForeignKey('Isapre', on_delete=models.SET_NULL, null=True, blank=True)
    afp = models.ForeignKey('AFP', on_delete=models.SET_NULL, null=True, blank=True, verbose_name='AFP')
    fecha_ingreso_docente = models.DateField(verbose_name='Fecha de ingreso como docente', null=True, blank=True)
    fecha_ingreso_sea = models.DateField(verbose_name='Fecha de ingreso al SEA', null=True, blank=True)
    estado = models.PositiveSmallIntegerField(default=1, choices=TIPO_FUNCIONARIO, verbose_name='Estado funcionario')
    tipo_misionero = models.PositiveSmallIntegerField(
        choices=TIPO_MISIONERO,
        null=True, blank=True,
        verbose_name='Tipo de Misionero'
    )
    puntos = models.PositiveIntegerField(default=0, null=True, blank=True)

    @staticmethod
    def contrato_vigente(id_colegio):
        colegio = get_object_or_404(
            Entidad,
            id=id_colegio
        )
        colegios = Entidad.objects.filter(dependiente=colegio.dependiente)

        return Contrato.objects.filter(entidad__in=colegios, vigente=True).exists()

    def __str__(self):
        return str(self.persona)

    class Meta:
        verbose_name = u'Funcionario'
        verbose_name_plural = u'Funcionarios'


class DatosBancarios(models.Model):
    TIPO_CUENTA = (
        (1, 'Cuenta vista'),
        (2, 'Cuenta corriente'),
        (3, 'Chequera electrónica')
    )
    funcionario = models.ForeignKey('Funcionario', on_delete=models.CASCADE)
    banco = models.ForeignKey(Banco, on_delete=models.CASCADE)
    tipo_cuenta = models.PositiveSmallIntegerField(default=1, choices=TIPO_CUENTA)
    numero = models.PositiveIntegerField()

    def __str__(self):
        return '{}, {} - {}'.format(
            self.funcionario.persona,
            self.tipo_cuenta,
            self.banco
        )

    class Meta:
        verbose_name = u'Documento de funcionario'
        verbose_name_plural = u'Documentos de funcionarios'

rrhh/templates/rrhh/entrevista/detalle_entrevista.html
    {% extends 'base/base.html' %}
{% load staticfiles %}

{% block title_page %}
    Entrevista - Detalle
{% endblock %}

{% block content %}

<div class="card">
    <div class="card-header">
      <h4 class="card-title"><strong> {{ object.funcionario }}</strong>
          {% block buttons %}
              <div class="btn-group float-right">
                  <a href="{% url 'rrhh:entrevistas' %}" type="button" class="btn btn-outline-info">
                      <i class="uil-arrow-left"></i>
                  </a>
                  <a href="{% url 'rrhh:entrevista__editar' object.pk %}" type="button" class="btn btn-outline-primary">
                      <i class="uil-edit"></i>
                  </a>
                  <a class="btn btn-outline-danger" href="#" data-toggle="modal" data-target="#eliminar_entrevista_{{object.pk}}">
                      <i class="uil-trash-alt"></i>
                  </a>
              </div>
          {% endblock %}
        </h4>
        <h6 class="card-subtitle mb-2 text-muted">Detalle de la entrevista</h6>

    </div>
    <div class="card-body">

		<div class="row">
        <div class="col-md-6">
            <table class="table table-hover table-sm">
                <thead>
                <tr>
                    <th colspan="2" class="table-info">
                <span>
                    <i class="uil-info-circle"></i>
                     Descripción
                </span>
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <th> Funcionario </th>
                    <td>  {{ object.contrato }}  </td>
                </tr>
                <tr>
                    <th> Entrevistador </th>
                    <td>  {{ object.entrevistador }}  </td>
                </tr>
                <tr>
                    <th> Tipo </th>
                    <td>  {{ object.get_tipo_display }}  </td>
                </tr>
                <tr>
                    <th> Contenido </th>
                    <td>  {{ object.contenido }}  </td>
                </tr>
                <tr>
                    <th> Acuerdos </th>
                    <td>  {{ object.acuerdos }}  </td>
                </tr>
                <!--
                <tr>
                    <td colspan="2">
                        <small class="text-muted">
                            Creado: {{ object.creado_en }}
                            <br>
                            Modificado: {{ object.modificado_en }}
                        </small>
                    </td>
                </tr>
                -->
                </tbody>
            </table>
        </div>

		  <div class="col-md-6">
		  </div>


	</div>

    </div>
  </div>
</div>

<div class="modal" tabindex="-1" role="dialog" id="eliminar_entrevista_{{object.pk}}">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title alert alert-warning bg-white text-warning" role="alert"><strong>¡Alerta!</strong> Está a punto de eliminar un Entrevista</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Está seguro que desea eliminar el entrevista "{{ object.nombre }}"?.</p>
                <p class="text-muted">Recuerde que eliminará todos los registros asociados a este entrevista.</p>
            </div>
            <div class="modal-footer">
                <a role="button" class="btn btn-danger" href="{% url 'rrhh:entrevista__eliminar' object.pk %}">Eliminar</a>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

rrhh/templates/rrhh/entrevista/editar_entrevista.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}


{% block content %}
<div class="card">
    <div class="card-header">
        <h4 class="card-title">Editar Entrevista
        </h4>
        <h6 class="card-subtitle mb-2 text-muted">Datos de la entrevista</h6>
    </div>
    <div class="card-body">

        <form class="form-horizontal" method="post" novalidate>
            {% csrf_token %}
            {% crispy form %}
            <div class="form-group">
                <div class="col-sm-10 col-sm-offset-2">
                    <button type="submit" class="btn btn-outline-success">Guardar</button>
                    <a href="{{ request.META.HTTP_REFERER }}"
                    role="button" class="btn btn-outline-info">
                        Volver
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

rrhh/templates/rrhh/entrevista/listado_entrevista.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% load bootstrap_pagination %}

{% block title_page %}
    Entrevistas
{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header">
        <h4 class="card-title">Entrevistas
          <a class="btn btn-outline-primary" href="{% url 'rrhh:entrevista__nuevo'%}" role="button">
	    <span>Crear Entrevista<i class="uil-plus"></i>
	    </span>
            </a>
        </h4>
        <h5 class="card-text mb-2 text-muted">Tabla para configuración de entrevistas</h5>
    </div>
    <div class="card-body">
        <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th><i class="uil-user text-muted font-weight-normal"></i> Entrevistado </th>
                <th><i class="uil-clock text-muted font-weight-normal"></i> Entrevistador </th>
                <th><i class="uil-clock text-muted font-weight-normal"></i> Tipo </th>
                <th><i class="mdi mdi-cogs text-muted font-weight-normal"></i> Acciones </th>
            </tr>
            </thead>
            <tbody>
            {% for p in object_list %}
                <tr>
                    <td><a href="{% url 'rrhh:entrevista' p.pk %}"> {{ p.contrato }} </a></td>
                    <td> {{ p.entrevistador }} </td>
                    <td> {{ p.get_tipo_display }} </td>
                    <td>
                        <a class="btn btn-outline-primary" href="{% url 'rrhh:entrevista__editar' p.pk %}" data-toggle="tooltip" data-placement="top" title="Editar"><i class="uil-edit"></i></a>
                        <a class="btn btn-outline-danger" href="#" data-toggle="modal" data-target="#eliminar_entrevista_{{p.pk}}"><i class="uil-trash-alt"></i></a>
                    </td>
                </tr>
                <div class="modal" tabindex="-1" role="dialog" id="eliminar_entrevista_{{p.pk}}">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title alert alert-warning bg-white text-warning" role="alert"><strong>¡Alerta!</strong> Está a punto de eliminar un Entrevista</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body alert alert-danger bg-white text-danger">
                                <p>Está seguro que desea eliminar el entrevista "{{ p.nombre }}"?.</p>
                                <p class="text-muted">Recuerde que eliminará todos los registros asociados a este entrevista.</p>
                            </div>
                            <div class="modal-footer">
                                <a role="button" class="btn btn-outline-danger" href="{% url 'rrhh:entrevista__eliminar' p.pk %}">Eliminar</a>
                                <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cerrar</button>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </tbody>
        </table>
    </div>

    </div>

                    <div class="card-footer">
                    <div align="center">
                        {% bootstrap_paginate page_obj range=5 %}
                    </div>
                </div>

</div>

{% endblock content  %}

rrhh/templates/rrhh/entrevista/nueva_entrevista.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}


{% block content %}
<div class="card">
    <div class="card-header">
        <h4 class="card-title page-title">Crear Entrevista
        </h4>
        <h6 class="font-weight-normal mb-2 text-muted">Datos de la entrevista</h6>
    </div>
    <div class="card-body">

        <form class="form-horizontal" method="post" novalidate>
            {% csrf_token %}
            {% crispy form %}
            <div class="form-group">
                <div class="col-sm-10 col-sm-offset-2">
                    <button type="submit" class="btn btn-outline-success">Guardar</button>
                    <a href="{{ request.META.HTTP_REFERER }}"
                    role="button" class="btn btn-outline-info">
                        Volver
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}